<?= $this->render('header.phtml'); ?>
	<?if($this->status):?>
		<?=$this->status?>
	<?endif;?>
	<?if($this->products):?>
		<?foreach($this->products as $product):?>
			<?=$product->title." ".$this->quantity[$product->id].'  '?><a href="/cart/removefromcart/id/<?=$product->id?>">Remove from cart</a>
			<br />
		<?endforeach;?>
		<?=$this->price?>
		<br />
		<a href="/cart/checkout">Buy</a>
		<br />
		<a href="/cart/emptycart">Empty cart</a>
	<?endif;?>
	<br />
	<a href="/">Home</a>
<?= $this->render('footer.phtml'); ?>