<?= $this->render('header.phtml'); ?>
	<?if($this->status):?>
		<?=$this->status?>
	<?endif;?>
	<?if($this->products):?>
		<?foreach($this->keys as $key):?>
			<?=$this->infos[$key]['title']." ".$this->products[$key]." "?><a href="/cart/removefromcart/id/<?=$key?>">Remove from cart</a>
			<br />
		<?endforeach;?>
		<?=$this->price?>
		<br />
		<a href="/cart/checkout">Buy</a>
		<br />
		<a href="/cart/emptycart">Empty cart</a>
	<?endif;?>
	<br />
	<a href="/">Home</a>
<?= $this->render('footer.phtml'); ?>