<?= $this->render('header.phtml'); ?>
    <table>
        <tr border="1">
            <th>Poza</th>
            <th>Nume produs</th>
            <th>Pret</th>
            <th>Detalii</th>
        </tr>                                      
        <? foreach ($this->products as $product): ?>
            <tr>
                <td><img src="uploads/<?= $product->id.$product->image ?>" class="img"></td>
                <td><?= $product->title ?></td>
                <td><?= $product->price ?></td>
                <td><?= $product->description ?></td>
            </tr>                                      
        <? endforeach; ?>
    </table>
    <br />
    <a href="/index/login">Login</a>
    <a href="/index/adauga">Adauga</a>
<?= $this->render('footer.phtml'); ?>