<?= $this->render('header.phtml'); ?>
    <a href='/index/test'>Test</a>
    <?if(isset($this->admin)):?>
        Logged as :<?=$this->admin?>
        <br />
        <a href="/list">Edit</a>
        <br />
        <a href="/index/logout">Logout</a>
    <?else:?>
        <a href="/index/login">Login</a>
    <?endif;?>
    <br />
    <a href="/cart">Cart</a>
    <br />
    <table>
        <tr border="1">
            <th>Poza</th>
            <th>Nume produs</th>
            <th>Pret</th>
            <th>Detalii</th>

        </tr>                                      
        <? foreach ($this->products as $product): ?>
            <tr>
                <td>
                    <?if($product->image):?>
                        <img src="uploads/<?= $product->id.$product->image ?>" class="img">
                    <?else:?>
                        <img src="uploads/images.png ?>" class="img">
                    <?endif;?>
                </td>
                <td><?= $product->title ?></td>
                <td><?= $product->price ?></td>
                <td><?= $product->description ?></td>
                <td><a href="/index/addtocart/id/<?=$product->id?>" >Add to cart</a></td>
            </tr>                                      
        <? endforeach; ?>
    </table>
    <br />
<?= $this->render('footer.phtml'); ?>