<?= $this->render('header.phtml'); ?>
	Logged as :<?=$this->admin?>
	<br />
	<a href='/'>Home</a>
	<br />
	<a href='/list/add'>Add</a>
	<br />
	<table>
        <tr border="1">
            <th>Poza</th>
            <th>Nume produs</th>
            <th>Pret</th>
            <th>Detalii</th>

        </tr>                                      
        <? foreach ($this->products as $product): ?>
            <tr>
                <td>
                    <?if($product->image):?>
                        <img src="uploads/<?= $product->id.$product->image ?>" class="img">
                    <?else:?>
                        <img src="uploads/images.png ?>" class="img">
                    <?endif;?>
                </td>
                <td><?= $product->title ?></td>
                <td><?= $product->price ?></td>
                <td><?= $product->description ?></td>
                <td><a href="/list/add/id/<?=$product->id?>" >Edit</a><a href="/list/remove/id/<?=$product->id?>" >Remove</a></td>
            </tr>                                      
        <? endforeach; ?>
    </table>
    <br />
<?= $this->render('footer.phtml'); ?>